import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Clock, Loader2, MapPin, Truck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export const Route = createFileRoute("/account/scrap-pickups")({ ssr: false, head: () => ({ meta: [{ title: "My scrap pickups | HuluMart" }, { name: "robots", content: "noindex, nofollow" }] }), component: ScrapPickups });
type Pickup = { id: string; scrap_mode: string; items: string[]; status: string; address: string | null; pincode: string | null; preferred_date: string | null; slot: string | null; name: string; phone: string; has_photo: boolean; photo_url: string | null; created_at: string };
const canCancel = (status: string) => ["new", "contacted", "scheduled"].includes(status);
const label = (status: string) => status === "new" ? "Pending" : status;

function ScrapPickups() {
  const { user, loading } = useAuth(); const qc = useQueryClient(); const [selected, setSelected] = useState<Pickup | null>(null);
  const { data: pickups = [], isLoading } = useQuery({ queryKey: ["my-scrap-pickups", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("leads").select("id, scrap_mode, items, status, address, pincode, preferred_date, slot, name, phone, has_photo, photo_url, created_at").eq("user_id", user!.id).order("created_at", { ascending: false }); if (error) throw error; return data as Pickup[]; } });
  const cancel = useMutation({ mutationFn: async (id: string) => { const { error } = await supabase.from("leads").delete().eq("id", id); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["my-scrap-pickups", user?.id] }); setSelected(null); toast.success("Scrap pickup cancelled."); }, onError: () => toast.error("Couldn't cancel this pickup.") });
  if (loading || isLoading) return <div className="flex justify-center py-20"><Loader2 className="size-6 animate-spin text-primary" /></div>;
  return <main className="bg-secondary/30"><div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-10"><h1 className="text-2xl font-bold">My scrap pickups</h1><p className="mt-1 text-sm text-muted-foreground">Your doorstep scrap collection requests.</p>{pickups.length === 0 ? <Empty /> : <div className="mt-5 space-y-3">{pickups.map((p) => <button key={p.id} type="button" onClick={() => setSelected(p)} className="w-full rounded-3xl border border-border bg-card p-5 text-left shadow-soft transition hover:border-primary/40"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-lg font-semibold">{p.scrap_mode === "mixed" ? "Mixed scrap pickup" : p.items.join(", ") || "Scrap pickup"}</p><p className="mt-1 text-sm text-muted-foreground">Tap to see pickup details</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold capitalize text-primary">{label(p.status)}</span>{canCancel(p.status) && <span role="button" aria-label="Cancel pickup" onClick={(e) => { e.stopPropagation(); if (window.confirm("Cancel this scrap pickup?")) cancel.mutate(p.id); }} className="rounded-full p-1 text-destructive hover:bg-destructive/10"><XCircle className="size-5" /></span>}</div></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-sm text-muted-foreground">{p.preferred_date && <span className="flex items-center gap-1"><CalendarDays className="size-3.5 text-primary" /> {p.preferred_date}</span>}{p.slot && <span className="flex items-center gap-1"><Clock className="size-3.5 text-primary" /> {p.slot}</span>}{p.pincode && <span className="flex items-center gap-1"><MapPin className="size-3.5 text-primary" /> {p.pincode}</span>}</div></button>)}</div>}</div><PickupDialog pickup={selected} onClose={() => setSelected(null)} onCancel={() => selected && cancel.mutate(selected.id)} cancelling={cancel.isPending} /></main>;
}
function PickupDialog({ pickup, onClose, onCancel, cancelling }: { pickup: Pickup | null; onClose: () => void; onCancel: () => void; cancelling: boolean }) { return <Dialog open={!!pickup} onOpenChange={(open) => !open && onClose()}><DialogContent className="bottom-0 top-auto max-h-[85dvh] w-full translate-y-0 rounded-t-3xl p-5 sm:left-1/2 sm:top-1/2 sm:max-w-md sm:-translate-x-1/2 sm:-translate-y-1/2 sm:rounded-2xl"><DialogHeader><DialogTitle>{pickup?.scrap_mode === "mixed" ? "Mixed scrap pickup" : pickup?.items.join(", ") || "Scrap pickup"}</DialogTitle><DialogDescription>{pickup ? `${label(pickup.status)} pickup request` : ""}</DialogDescription></DialogHeader>{pickup && <div className="space-y-3 overflow-y-auto pr-1 text-sm"><Row label="Items" value={pickup.scrap_mode === "mixed" ? "Mixed household scrap" : pickup.items.join(", ")} /><Row label="Pickup" value={[pickup.preferred_date, pickup.slot].filter(Boolean).join(", ") || "Not scheduled"} /><Row label="Address" value={[pickup.address, pickup.pincode].filter(Boolean).join(", ") || "Not added"} /><Row label="Contact" value={`${pickup.name} · ${pickup.phone}`} />{pickup.photo_url && <img src={pickup.photo_url} alt="Pickup item" className="max-h-44 w-full rounded-xl object-cover" />}{canCancel(pickup.status) && <Button variant="outline" className="mt-2 w-full text-destructive" disabled={cancelling} onClick={() => { if (window.confirm("Cancel this scrap pickup?")) onCancel(); }}><XCircle className="size-4" /> Cancel pickup</Button>}</div>}</DialogContent></Dialog>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-secondary/60 px-3 py-2.5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-0.5 break-words font-medium">{value}</p></div>; }
function Empty() { return <div className="mt-6 rounded-3xl border border-dashed border-border bg-card p-10 text-center"><Truck className="mx-auto size-9 text-muted-foreground" /><p className="mt-3 font-semibold">No scrap pickups yet</p><Button asChild variant="hero" className="mt-5"><Link to="/pickup">Book a pickup</Link></Button></div>; }
