import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Clock, Laptop, Loader2, MapPin, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export const Route = createFileRoute("/account/laptop-orders")({ ssr: false, head: () => ({ meta: [{ title: "My laptop quotes | HuluMart" }, { name: "robots", content: "noindex, nofollow" }] }), component: LaptopOrders });
type Order = { id: string; model_name: string | null; brand_name: string | null; series_name: string | null; base_price: number; final_price: number; status: string; name: string; phone: string; email: string | null; address: string | null; pincode: string | null; preferred_date: string | null; slot: string | null; notes: string | null; created_at: string };
const canCancel = (status: string) => ["new", "contacted", "scheduled"].includes(status);
const label = (status: string) => status === "new" ? "Pending" : status;
const money = (value: number) => `₹${Number(value).toLocaleString("en-IN")}`;

function LaptopOrders() {
  const { user, loading } = useAuth(); const qc = useQueryClient(); const [selected, setSelected] = useState<Order | null>(null);
  const { data: orders = [], isLoading } = useQuery({ queryKey: ["my-device-orders", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("device_orders").select("id, model_name, brand_name, series_name, base_price, final_price, status, name, phone, email, address, pincode, preferred_date, slot, notes, created_at").eq("user_id", user!.id).order("created_at", { ascending: false }); if (error) throw error; return data as Order[]; } });
  const cancel = useMutation({ mutationFn: async (id: string) => { const { error } = await supabase.from("device_orders").update({ status: "cancelled" }).eq("id", id); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["my-device-orders", user?.id] }); setSelected(null); toast.success("Laptop pickup cancelled."); }, onError: () => toast.error("Couldn't cancel this pickup.") });
  if (loading || isLoading) return <div className="flex justify-center py-20"><Loader2 className="size-6 animate-spin text-primary" /></div>;
  return <main className="bg-secondary/30"><div className="mx-auto max-w-3xl px-4 py-8 sm:px-6 sm:py-10"><h1 className="text-2xl font-bold">My laptop quotes</h1><p className="mt-1 text-sm text-muted-foreground">Your laptop valuation and pickup requests.</p>{orders.length === 0 ? <Empty /> : <div className="mt-5 space-y-3">{orders.map((o) => <button key={o.id} type="button" onClick={() => setSelected(o)} className="w-full rounded-3xl border border-border bg-card p-5 text-left shadow-soft transition hover:border-primary/40"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-lg font-semibold">{o.model_name || "Laptop"}</p><p className="mt-1 truncate text-sm text-muted-foreground">{[o.brand_name, o.series_name].filter(Boolean).join(" · ")}</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold capitalize text-primary">{label(o.status)}</span>{canCancel(o.status) && <span role="button" aria-label="Cancel pickup" onClick={(e) => { e.stopPropagation(); if (window.confirm("Cancel this laptop pickup?")) cancel.mutate(o.id); }} className="rounded-full p-1 text-destructive hover:bg-destructive/10"><XCircle className="size-5" /></span>}</div></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-sm text-muted-foreground">{o.preferred_date && <span className="flex items-center gap-1"><CalendarDays className="size-3.5 text-primary" /> {o.preferred_date}</span>}{o.slot && <span className="flex items-center gap-1"><Clock className="size-3.5 text-primary" /> {o.slot}</span>}{o.pincode && <span className="flex items-center gap-1"><MapPin className="size-3.5 text-primary" /> {o.pincode}</span>}</div></button>)}</div>}</div><OrderDialog order={selected} onClose={() => setSelected(null)} onCancel={() => selected && cancel.mutate(selected.id)} cancelling={cancel.isPending} /></main>;
}
function OrderDialog({ order, onClose, onCancel, cancelling }: { order: Order | null; onClose: () => void; onCancel: () => void; cancelling: boolean }) { return <Dialog open={!!order} onOpenChange={(open) => !open && onClose()}><DialogContent className="bottom-0 top-auto max-h-[85dvh] w-full translate-y-0 rounded-t-3xl p-5 sm:left-1/2 sm:top-1/2 sm:max-w-md sm:-translate-x-1/2 sm:-translate-y-1/2 sm:rounded-2xl"><DialogHeader><DialogTitle>{order?.model_name || "Laptop quote"}</DialogTitle><DialogDescription>{order ? `${label(order.status)} · ${money(order.final_price)} quoted value` : ""}</DialogDescription></DialogHeader>{order && <div className="space-y-3 overflow-y-auto pr-1 text-sm"><Row label="Model" value={[order.brand_name, order.series_name, order.model_name].filter(Boolean).join(" · ")} /><Row label="Pickup" value={[order.preferred_date, order.slot].filter(Boolean).join(", ") || "Not scheduled"} /><Row label="Address" value={[order.address, order.pincode].filter(Boolean).join(", ") || "Not added"} /><Row label="Contact" value={[order.name, order.phone, order.email].filter(Boolean).join(" · ")} /><Row label="Quote" value={`${money(order.final_price)}${order.base_price !== order.final_price ? ` (base ${money(order.base_price)})` : ""}`} />{order.notes && <Row label="Notes" value={order.notes} />}{canCancel(order.status) && <Button variant="outline" className="mt-2 w-full text-destructive" disabled={cancelling} onClick={() => { if (window.confirm("Cancel this laptop pickup?")) onCancel(); }}><XCircle className="size-4" /> Cancel pickup</Button>}</div>}</DialogContent></Dialog>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-secondary/60 px-3 py-2.5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-0.5 break-words font-medium">{value}</p></div>; }
function Empty() { return <div className="mt-6 rounded-3xl border border-dashed border-border bg-card p-10 text-center"><Laptop className="mx-auto size-9 text-muted-foreground" /><p className="mt-3 font-semibold">No laptop quotes yet</p><Button asChild variant="hero" className="mt-5"><Link to="/sell/laptops">Get a laptop quote</Link></Button></div>; }
