import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { CalendarDays, Clock, Loader2, MapPin, Truck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/account/scrap-pickups")({ ssr: false, head: () => ({ meta: [{ title: "My scrap pickups | HuluMart" }, { name: "robots", content: "noindex, nofollow" }] }), component: ScrapPickups });
function ScrapPickups() { const { user, loading } = useAuth(); const { data: pickups = [], isLoading } = useQuery({ queryKey: ["my-scrap-pickups", user?.id], enabled: !!user, queryFn: async () => { const { data, error } = await supabase.from("leads").select("id, scrap_mode, items, status, address, pincode, preferred_date, slot").eq("user_id", user!.id).order("created_at", { ascending: false }); if (error) throw error; return data; } }); if (loading) return <div className="flex justify-center py-20"><Loader2 className="size-6 animate-spin text-primary" /></div>; return <main className="bg-secondary/30"><div className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><h1 className="text-2xl font-bold">My scrap pickups</h1><p className="mt-1 text-sm text-muted-foreground">Your doorstep scrap collection requests.</p>{isLoading ? <div className="flex justify-center py-12"><Loader2 className="size-6 animate-spin text-primary" /></div> : pickups.length === 0 ? <div className="mt-6 rounded-3xl border border-dashed border-border bg-card p-10 text-center"><Truck className="mx-auto size-9 text-muted-foreground" /><p className="mt-3 font-semibold">No scrap pickups yet</p><Button asChild variant="hero" className="mt-5"><Link to="/pickup">Book a pickup</Link></Button></div> : <div className="mt-6 space-y-3">{pickups.map((p) => <div key={p.id} className="rounded-2xl border border-border bg-card p-5 shadow-soft"><div className="flex justify-between gap-3"><p className="font-semibold">{p.scrap_mode === "mixed" ? "Mixed scrap pickup" : p.items?.join(", ") || "Scrap pickup"}</p><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-bold capitalize text-primary">{p.status}</span></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-1.5 text-sm text-muted-foreground">{p.preferred_date && <span className="flex items-center gap-1"><CalendarDays className="size-3.5 text-primary" /> {p.preferred_date}</span>}{p.slot && <span className="flex items-center gap-1"><Clock className="size-3.5 text-primary" /> {p.slot}</span>}{(p.address || p.pincode) && <span className="flex items-center gap-1"><MapPin className="size-3.5 text-primary" /> {[p.address, p.pincode].filter(Boolean).join(", ")}</span>}</div></div>)}</div>}</div></main>; }
