import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ImagePlus, Loader2, Pencil, Plus, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import carImg from "@/assets/vehicle-car.webp";
import bikeImg from "@/assets/vehicle-bike.webp";
import scooterImg from "@/assets/vehicle-scooter.webp";
import commercialImg from "@/assets/vehicle-commercial.webp";
import suvImg from "@/assets/vehicle-suv.webp";

type Item = { id: string; name: string; image_url: string | null; active: boolean; sort_order: number; category_id?: string };
const db = supabase as unknown as { from: (table: string) => any };
const defaults = (name: string) => ({ Car: carImg, Bike: bikeImg, Scooter: scooterImg, "Commercial vehicle": commercialImg, SUV: suvImg }[name] ?? null);
const imageFile = (file: File) => new Promise<string>((ok, bad) => { const r = new FileReader(); r.onload = () => ok(String(r.result)); r.onerror = () => bad(new Error("Couldn’t read image.")); r.readAsDataURL(file); });

export function CatalogueTaxonomyPanel({ kind }: { kind: "categories" | "subcategories" }) {
  const isType = kind === "subcategories"; const table = isType ? "vehicle_subcategories" : "vehicle_categories"; const qc = useQueryClient(); const [parent, setParent] = useState(""); const [editing, setEditing] = useState<Item | null | "new">(null);
  const cats = useQuery({ queryKey: ["admin", "cats"], queryFn: async () => { const { data, error } = await db.from("vehicle_categories").select("id,name,image_url,active,sort_order").order("sort_order"); if (error) throw error; return data as Item[]; } });
  const list = useQuery({ queryKey: ["admin", table, parent], queryFn: async () => { const fields = isType ? "id,name,image_url,active,sort_order,category_id" : "id,name,image_url,active,sort_order"; let q = db.from(table).select(fields).order("sort_order").order("name"); if (isType && parent) q = q.eq("category_id", parent); const { data, error } = await q; if (error) throw error; return data as Item[]; } });
  const refresh = () => qc.invalidateQueries({ queryKey: ["admin"] });
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-card p-4"><div><h2 className="font-bold">{isType ? "Vehicle types" : "Vehicle categories"}</h2><p className="mt-1 text-sm text-muted-foreground">Image cards used in booking.</p></div><Button variant="hero" onClick={() => setEditing("new")}><Plus className="size-4" /> Create {isType ? "type" : "category"}</Button></div>{isType && <Select value={parent} onValueChange={setParent}><SelectTrigger className="h-12 max-w-md rounded-xl"><SelectValue placeholder="Choose parent category" /></SelectTrigger><SelectContent>{(cats.data ?? []).map(c => <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select>}{list.isLoading ? <div className="flex justify-center py-16"><Loader2 className="animate-spin" /></div> : list.error ? <p className="rounded-xl border border-destructive/30 p-4 text-destructive">Couldn’t load cards. Refresh and try again.</p> : <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(list.data ?? []).map(item => <Card key={item.id} item={item} table={table} edit={() => setEditing(item)} changed={refresh} />)}</div>}<Editor open={editing !== null} item={editing === "new" ? null : editing} isType={isType} selectedParent={parent} categories={cats.data ?? []} close={() => setEditing(null)} saved={refresh} /></div>;
}
function Card({ item, table, edit, changed }: { item: Item; table: string; edit: () => void; changed: () => void }) { const toggle = useMutation({ mutationFn: async (active: boolean) => { const { error } = await db.from(table).update({ active }).eq("id", item.id); if (error) throw error; }, onSuccess: changed }); const remove = useMutation({ mutationFn: async () => { const { error } = await db.from(table).delete().eq("id", item.id); if (error) throw error; }, onSuccess: changed }); const image = item.image_url || defaults(item.name); return <article className="overflow-hidden rounded-3xl border bg-card"><div className="relative flex aspect-[16/8] items-center justify-center bg-secondary/50">{image ? <img src={image} alt="" className="size-full object-cover" /> : <ImagePlus className="size-7 text-muted-foreground" />}<Button size="icon" variant="secondary" className="absolute right-3 top-3 rounded-full" onClick={edit}><Pencil className="size-4" /></Button></div><div className="flex items-center gap-2 p-3"><span className="flex-1 font-semibold">{item.name}</span><Switch checked={item.active} onCheckedChange={a => toggle.mutate(a)} /><Button size="icon" variant="ghost" className="text-destructive" onClick={() => remove.mutate()}><Trash2 className="size-4" /></Button></div></article>; }
function Editor({ open, item, isType, selectedParent, categories, close, saved }: { open: boolean; item: Item | null; isType: boolean; selectedParent: string; categories: Item[]; close: () => void; saved: () => void }) { const table = isType ? "vehicle_subcategories" : "vehicle_categories"; const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [position, setPosition] = useState("0"); const [parent, setParent] = useState(""); useEffect(() => { if (open) { setName(item?.name ?? ""); setUrl(item?.image_url ?? ""); setPosition(String(item?.sort_order ?? 0)); setParent(item?.category_id ?? selectedParent); } }, [open, item, selectedParent]); const save = useMutation({ mutationFn: async () => { const value = { name: name.trim(), image_url: url || null, sort_order: Number(position) || 0, ...(isType ? { category_id: parent } : {}) }; const { error } = item ? await db.from(table).update(value).eq("id", item.id) : await db.from(table).insert(value); if (error) throw error; }, onSuccess: () => { saved(); close(); toast.success("Card saved."); }, onError: (e: Error) => toast.error(e.message) }); return <Dialog open={open} onOpenChange={v => !v && close()}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-3xl sm:max-w-md"><DialogHeader><DialogTitle>{item ? "Edit" : "Create"} {isType ? "vehicle type" : "category"}</DialogTitle><DialogDescription>Compact card settings for desktop and mobile.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Name</Label><Input className="mt-2" value={name} onChange={e => setName(e.target.value)} /></div>{isType && <div><Label>Parent category</Label><Select value={parent} onValueChange={setParent}><SelectTrigger className="mt-2"><SelectValue placeholder="Choose category" /></SelectTrigger><SelectContent>{categories.map(c => <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>}<div><Label>Display position</Label><Input className="mt-2" type="number" min="0" value={position} onChange={e => setPosition(e.target.value)} /></div><div><Label>Image URL</Label><Input className="mt-2" value={url.startsWith("data:") ? "Image uploaded" : url} placeholder="https://…" onChange={e => setUrl(e.target.value)} /></div><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border-2 border-dashed p-4 text-sm font-semibold"><Upload className="size-4" /> Upload image<input className="hidden" type="file" accept="image/*" onChange={async e => { const f = e.target.files?.[0]; if (f) setUrl(await imageFile(f)); }} /></label>{url && <img src={url} alt="Preview" className="h-32 w-full rounded-xl object-cover" />}<Button className="w-full" variant="hero" disabled={!name.trim() || (isType && !parent) || save.isPending} onClick={() => save.mutate()}>{save.isPending ? <Loader2 className="animate-spin" /> : "Save card"}</Button></div></DialogContent></Dialog>; }
