import Link from "next/link";
import { ArrowRight, Car, ClipboardCheck, Handshake, MapPin, ShieldCheck, Wallet } from "lucide-react";
import { PageHeader } from "@/components/PageHeader";
import { businessContact } from "@/lib/seo";

const principles = [
  { icon: ClipboardCheck, title: "Clear information", text: "We explain the steps from vehicle details to inspection, offer discussion and handover so owners know what to expect." },
  { icon: Handshake, title: "Respect for your decision", text: "An inspection and an offer are part of your evaluation. You decide whether the terms work for you." },
  { icon: ShieldCheck, title: "Responsible handover", text: "We help owners understand the paperwork, payment and ownership-transfer steps involved in completing a sale." },
];

export default function About() {
  return <main className="bg-background">
    <PageHeader eyebrow="About Zapiboo" title={<>A clearer way to <span className="text-gradient">sell your vehicle.</span></>} subtitle="Zapiboo helps vehicle owners in Bangalore start the selling process with an inspection-led, straightforward experience." />
    <section className="border-b border-border py-14 sm:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8"><div><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Built around a practical selling journey</h2><p className="mt-5 leading-relaxed text-muted-foreground">Selling a used car, bike or scooter can involve figuring out a fair starting point, arranging an inspection, discussing an offer and preparing the documents for handover. Zapiboo is built to make those steps easier to follow for owners in Bangalore.</p><p className="mt-4 leading-relaxed text-muted-foreground">Start online with your vehicle details, select an available appointment, and meet the team for an inspection. We aim to give you a clear next step at every stage, without asking you to manage a fragmented selling process alone.</p><Link href="/pickup" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground hover:bg-primary/90">Book a free inspection <ArrowRight className="size-4" /></Link></div><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">{[[Car, "Cars, bikes and scooters"], [MapPin, "Bangalore-focused service"], [Wallet, "Offer discussion after inspection"]].map(([Icon, text]) => { const ItemIcon = Icon as typeof Car; return <div key={String(text)} className="rounded-2xl border border-border bg-card p-5"><ItemIcon className="size-7 text-primary" /><p className="mt-4 font-bold">{String(text)}</p></div>; })}</div></div></section>
    <section className="bg-secondary/35 py-14 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-wider text-primary">How we work</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Our approach is simple</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{principles.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-border bg-card p-6"><Icon className="size-7 text-primary" /><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{text}</p></article>)}</div></div></section>
    <section className="border-b border-border py-14 sm:py-20"><div className="mx-auto max-w-3xl px-4 sm:px-6"><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">What you can expect</h2><div className="mt-7 space-y-5 text-muted-foreground"><p>We ask for accurate vehicle and contact information so an inspection can be arranged properly. During the visit, the vehicle, its condition and available documents are reviewed. This information helps create a more useful basis for an offer discussion than a broad online estimate alone.</p><p>Vehicle selling can involve different requirements depending on the registration, ownership, finance status and condition of the vehicle. We encourage owners to ask questions, keep records together and confirm the details that apply to their sale before agreeing to a handover.</p><p>Zapiboo does not require you to accept an offer simply because you have requested an inspection. Our goal is to give you the information and support needed to make an informed decision.</p></div></div></section>
    <section className="bg-[#121112] py-14 text-white sm:py-20"><div className="mx-auto max-w-3xl px-4 text-center sm:px-6"><h2 className="text-3xl font-bold sm:text-4xl">Speak with the Zapiboo team</h2><p className="mx-auto mt-4 max-w-xl text-white/70">For a question about your vehicle, inspection availability or the selling process, call or email us directly.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><a href={businessContact.phoneHref} className="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">{businessContact.phone}</a><a href={businessContact.emailHref} className="rounded-xl border border-white/25 px-5 py-3 text-sm font-bold">{businessContact.email}</a></div></div></section>
  </main>;
}
