/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellCategoryRouteImport } from './routes/sell.$category'
import { Route as SellUsedLaptopAreaRouteImport } from './routes/sell-used-laptop.$area'
import { Route as SellOldLaptopBrandRouteImport } from './routes/sell-old-laptop.$brand'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as ApiKeepaliveRouteImport } from './routes/api.keepalive'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as SellCategoryBrandRouteImport } from './routes/sell.$category_.$brand'
import { Route as SellOldLaptopBrandModelRouteImport } from './routes/sell-old-laptop.$brand_.$model'
import { Route as SellCategoryBrandSeriesRouteImport } from './routes/sell.$category_.$brand_.$series'
import { Route as SellCategoryBrandSeriesModelRouteImport } from './routes/sell.$category_.$brand_.$series_.$model'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellCategoryRoute = SellCategoryRouteImport.update({
  id: '/sell/$category',
  path: '/sell/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SellUsedLaptopAreaRoute = SellUsedLaptopAreaRouteImport.update({
  id: '/sell-used-laptop/$area',
  path: '/sell-used-laptop/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const SellOldLaptopBrandRoute = SellOldLaptopBrandRouteImport.update({
  id: '/sell-old-laptop/$brand',
  path: '/sell-old-laptop/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeepaliveRoute = ApiKeepaliveRouteImport.update({
  id: '/api/keepalive',
  path: '/api/keepalive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellCategoryBrandRoute = SellCategoryBrandRouteImport.update({
  id: '/sell/$category_/$brand',
  path: '/sell/$category/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const SellOldLaptopBrandModelRoute = SellOldLaptopBrandModelRouteImport.update({
  id: '/sell-old-laptop/$brand_/$model',
  path: '/sell-old-laptop/$brand/$model',
  getParentRoute: () => rootRouteImport,
} as any)
const SellCategoryBrandSeriesRoute = SellCategoryBrandSeriesRouteImport.update({
  id: '/sell/$category_/$brand_/$series',
  path: '/sell/$category/$brand/$series',
  getParentRoute: () => rootRouteImport,
} as any)
const SellCategoryBrandSeriesModelRoute =
  SellCategoryBrandSeriesModelRouteImport.update({
    id: '/sell/$category_/$brand_/$series_/$model',
    path: '/sell/$category/$brand/$series/$model',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sell-old-laptop/$brand': typeof SellOldLaptopBrandRoute
  '/sell-used-laptop/$area': typeof SellUsedLaptopAreaRoute
  '/sell/$category': typeof SellCategoryRoute
  '/sell-old-laptop/$brand/$model': typeof SellOldLaptopBrandModelRoute
  '/sell/$category/$brand': typeof SellCategoryBrandRoute
  '/sell/$category/$brand/$series': typeof SellCategoryBrandSeriesRoute
  '/sell/$category/$brand/$series/$model': typeof SellCategoryBrandSeriesModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/sell-old-laptop/$brand': typeof SellOldLaptopBrandRoute
  '/sell-used-laptop/$area': typeof SellUsedLaptopAreaRoute
  '/sell/$category': typeof SellCategoryRoute
  '/sell-old-laptop/$brand/$model': typeof SellOldLaptopBrandModelRoute
  '/sell/$category/$brand': typeof SellCategoryBrandRoute
  '/sell/$category/$brand/$series': typeof SellCategoryBrandSeriesRoute
  '/sell/$category/$brand/$series/$model': typeof SellCategoryBrandSeriesModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/keepalive': typeof ApiKeepaliveRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/sell-old-laptop/$brand': typeof SellOldLaptopBrandRoute
  '/sell-used-laptop/$area': typeof SellUsedLaptopAreaRoute
  '/sell/$category': typeof SellCategoryRoute
  '/sell-old-laptop/$brand_/$model': typeof SellOldLaptopBrandModelRoute
  '/sell/$category_/$brand': typeof SellCategoryBrandRoute
  '/sell/$category_/$brand_/$series': typeof SellCategoryBrandSeriesRoute
  '/sell/$category_/$brand_/$series_/$model': typeof SellCategoryBrandSeriesModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/keepalive'
    | '/blog/$slug'
    | '/sell-old-laptop/$brand'
    | '/sell-used-laptop/$area'
    | '/sell/$category'
    | '/sell-old-laptop/$brand/$model'
    | '/sell/$category/$brand'
    | '/sell/$category/$brand/$series'
    | '/sell/$category/$brand/$series/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/keepalive'
    | '/blog/$slug'
    | '/sell-old-laptop/$brand'
    | '/sell-used-laptop/$area'
    | '/sell/$category'
    | '/sell-old-laptop/$brand/$model'
    | '/sell/$category/$brand'
    | '/sell/$category/$brand/$series'
    | '/sell/$category/$brand/$series/$model'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/keepalive'
    | '/blog_/$slug'
    | '/sell-old-laptop/$brand'
    | '/sell-used-laptop/$area'
    | '/sell/$category'
    | '/sell-old-laptop/$brand_/$model'
    | '/sell/$category_/$brand'
    | '/sell/$category_/$brand_/$series'
    | '/sell/$category_/$brand_/$series_/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiKeepaliveRoute: typeof ApiKeepaliveRoute
  BlogSlugRoute: typeof BlogSlugRoute
  SellOldLaptopBrandRoute: typeof SellOldLaptopBrandRoute
  SellUsedLaptopAreaRoute: typeof SellUsedLaptopAreaRoute
  SellCategoryRoute: typeof SellCategoryRoute
  SellOldLaptopBrandModelRoute: typeof SellOldLaptopBrandModelRoute
  SellCategoryBrandRoute: typeof SellCategoryBrandRoute
  SellCategoryBrandSeriesRoute: typeof SellCategoryBrandSeriesRoute
  SellCategoryBrandSeriesModelRoute: typeof SellCategoryBrandSeriesModelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$category': {
      id: '/sell/$category'
      path: '/sell/$category'
      fullPath: '/sell/$category'
      preLoaderRoute: typeof SellCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-used-laptop/$area': {
      id: '/sell-used-laptop/$area'
      path: '/sell-used-laptop/$area'
      fullPath: '/sell-used-laptop/$area'
      preLoaderRoute: typeof SellUsedLaptopAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-old-laptop/$brand': {
      id: '/sell-old-laptop/$brand'
      path: '/sell-old-laptop/$brand'
      fullPath: '/sell-old-laptop/$brand'
      preLoaderRoute: typeof SellOldLaptopBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keepalive': {
      id: '/api/keepalive'
      path: '/api/keepalive'
      fullPath: '/api/keepalive'
      preLoaderRoute: typeof ApiKeepaliveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$category_/$brand': {
      id: '/sell/$category_/$brand'
      path: '/sell/$category/$brand'
      fullPath: '/sell/$category/$brand'
      preLoaderRoute: typeof SellCategoryBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-old-laptop/$brand_/$model': {
      id: '/sell-old-laptop/$brand_/$model'
      path: '/sell-old-laptop/$brand/$model'
      fullPath: '/sell-old-laptop/$brand/$model'
      preLoaderRoute: typeof SellOldLaptopBrandModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$category_/$brand_/$series': {
      id: '/sell/$category_/$brand_/$series'
      path: '/sell/$category/$brand/$series'
      fullPath: '/sell/$category/$brand/$series'
      preLoaderRoute: typeof SellCategoryBrandSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/$category_/$brand_/$series_/$model': {
      id: '/sell/$category_/$brand_/$series_/$model'
      path: '/sell/$category/$brand/$series/$model'
      fullPath: '/sell/$category/$brand/$series/$model'
      preLoaderRoute: typeof SellCategoryBrandSeriesModelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiKeepaliveRoute: ApiKeepaliveRoute,
  BlogSlugRoute: BlogSlugRoute,
  SellOldLaptopBrandRoute: SellOldLaptopBrandRoute,
  SellUsedLaptopAreaRoute: SellUsedLaptopAreaRoute,
  SellCategoryRoute: SellCategoryRoute,
  SellOldLaptopBrandModelRoute: SellOldLaptopBrandModelRoute,
  SellCategoryBrandRoute: SellCategoryBrandRoute,
  SellCategoryBrandSeriesRoute: SellCategoryBrandSeriesRoute,
  SellCategoryBrandSeriesModelRoute: SellCategoryBrandSeriesModelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
