// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wizweflimtblfiiqspgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpendlZmxpbXRibGZpaXFzcGdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgxNjc0MDksImV4cCI6MjEwMzc0MzQwOX0.OLhCQ72SR6rR-vuSkyutwjPzLv5PyK_ynPSM9zhWSzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});