// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypdeyaxawswlztrdacij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZGV5YXhhd3N3bHp0cmRhY2lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODExOTg5MzcsImV4cCI6MjA5Njc3NDkzN30.cgylADCQ-zz9G_T1BrWpNjhjmHhv8VJ5Kl7AoL2fY_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});